# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 854)
        MainWindow.setStyleSheet("background:rgb(24,24,24);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 1221, 801))
        self.frame.setStyleSheet("\n"
"#frame{\n"
"\n"
"background:rgb(128, 196, 255);\n"
"\n"
"\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.footer_frame = QtWidgets.QFrame(self.frame)
        self.footer_frame.setGeometry(QtCore.QRect(0, 700, 1221, 91))
        self.footer_frame.setStyleSheet("background:rgb(0, 170, 155);")
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.label_11 = QtWidgets.QLabel(self.footer_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 81, 71))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("res/Icons/shine.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.footer_frame)
        self.label_12.setGeometry(QtCore.QRect(100, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("font-size:30px;\n"
"")
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.footer_frame)
        self.label_16.setGeometry(QtCore.QRect(90, 50, 331, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Std")
        font.setPointSize(-1)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("\n"
"font-size:14px;")
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setIndent(5)
        self.label_16.setOpenExternalLinks(False)
        self.label_16.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.footer_frame)
        self.label_17.setGeometry(QtCore.QRect(960, 55, 121, 31))
        self.label_17.setStyleSheet("font-size:15px;\n"
"\n"
"color:white;")
        self.label_17.setOpenExternalLinks(True)
        self.label_17.setObjectName("label_17")
        self.stacked_frame = QtWidgets.QStackedWidget(self.frame)
        self.stacked_frame.setGeometry(QtCore.QRect(0, 130, 1221, 571))
        self.stacked_frame.setMouseTracking(False)
        self.stacked_frame.setAcceptDrops(True)
        self.stacked_frame.setAutoFillBackground(False)
        self.stacked_frame.setStyleSheet("background:white;")
        self.stacked_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stacked_frame.setLineWidth(1)
        self.stacked_frame.setMidLineWidth(-1)
        self.stacked_frame.setObjectName("stacked_frame")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(570, 60, 131, 41))
        self.pushButton.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:13px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.preview_label1 = QtWidgets.QLabel(self.page)
        self.preview_label1.setGeometry(QtCore.QRect(60, 290, 331, 201))
        self.preview_label1.setAcceptDrops(True)
        self.preview_label1.setStyleSheet("border:4px solid white;\n"
"border-radius:3px;")
        self.preview_label1.setText("")
        self.preview_label1.setPixmap(QtGui.QPixmap("../../java_codes/124257240_3161320557306202_7239468197628284308_o.jpg"))
        self.preview_label1.setScaledContents(True)
        self.preview_label1.setObjectName("preview_label1")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(60, 60, 491, 41))
        self.label.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:18px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.label.setObjectName("label")
        self.preview_text_label1 = QtWidgets.QLabel(self.page)
        self.preview_text_label1.setGeometry(QtCore.QRect(130, 210, 151, 31))
        self.preview_text_label1.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:17px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"")
        self.preview_text_label1.setObjectName("preview_text_label1")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(770, 40, 20, 521))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(21)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 110, 91, 91))
        self.pushButton_2.setStyleSheet("\n"
"border:5px solid black;\n"
"border-radius:45px;\n"
"background:cyan;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(900, 60, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(800, 230, 101, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(900, 290, 141, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(50, 260, 61, 16))
        self.label_8.setStyleSheet("font-size:18px;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(10, 300, 51, 21))
        self.label_9.setStyleSheet("font-size:18px;")
        self.label_9.setObjectName("label_9")
        self.horizontalSlider = QtWidgets.QSlider(self.page)
        self.horizontalSlider.setGeometry(QtCore.QRect(800, 330, 191, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(1020, 310, 51, 51))
        self.pushButton_3.setStyleSheet("\n"
"border:2px solid black;\n"
"border-radius:25px;\n"
"background:cyan;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(790, 410, 301, 20))
        self.line_2.setLineWidth(3)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(790, 430, 301, 20))
        self.line_3.setLineWidth(3)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(790, 260, 301, 20))
        self.line_4.setLineWidth(3)
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.page)
        self.line_5.setGeometry(QtCore.QRect(790, 270, 301, 20))
        self.line_5.setLineWidth(3)
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.page)
        self.line_6.setGeometry(QtCore.QRect(790, 210, 301, 20))
        self.line_6.setLineWidth(3)
        self.line_6.setMidLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.instruction_message1 = QtWidgets.QLabel(self.page)
        self.instruction_message1.setGeometry(QtCore.QRect(30, 10, 581, 21))
        self.instruction_message1.setStyleSheet("\n"
"\n"
"font-size:15px;\n"
"font-family:Georgia;\n"
"\n"
"")
        self.instruction_message1.setObjectName("instruction_message1")
        self.highlightor_star1 = QtWidgets.QLabel(self.page)
        self.highlightor_star1.setGeometry(QtCore.QRect(0, 10, 31, 21))
        self.highlightor_star1.setStyleSheet("color:red;\n"
"font-size:25px;\n"
"font-family:Georgia;")
        self.highlightor_star1.setObjectName("highlightor_star1")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(130, 250, 201, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("res/Icons/horizontalarrow.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 31, 171))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("res/Icons/verticalarrow.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.preview_label1_2 = QtWidgets.QLabel(self.page)
        self.preview_label1_2.setGeometry(QtCore.QRect(420, 290, 331, 201))
        self.preview_label1_2.setAcceptDrops(True)
        self.preview_label1_2.setStyleSheet("border:4px solid white;\n"
"border-radius:3px;")
        self.preview_label1_2.setText("")
        self.preview_label1_2.setPixmap(QtGui.QPixmap("../../java_codes/s20-moon1.webp"))
        self.preview_label1_2.setScaledContents(True)
        self.preview_label1_2.setObjectName("preview_label1_2")
        self.preview_text_label1_2 = QtWidgets.QLabel(self.page)
        self.preview_text_label1_2.setGeometry(QtCore.QRect(520, 210, 151, 31))
        self.preview_text_label1_2.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:17px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"")
        self.preview_text_label1_2.setObjectName("preview_text_label1_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.page)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(900, 230, 171, 22))
        self.comboBox_2.setMaxVisibleItems(5)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(800, 380, 101, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(1000, 450, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(990, 540, 101, 20))
        self.label_10.setObjectName("label_10")
        self.comboBox_3 = QtWidgets.QComboBox(self.page)
        self.comboBox_3.setGeometry(QtCore.QRect(970, 480, 121, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.page)
        self.comboBox_4.setEnabled(False)
        self.comboBox_4.setGeometry(QtCore.QRect(800, 480, 131, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QtCore.QRect(820, 450, 91, 21))
        self.label_18.setObjectName("label_18")
        self.stacked_frame.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(70, 60, 411, 41))
        self.label_13.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:18px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.label_13.setObjectName("label_13")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 60, 131, 41))
        self.pushButton_6.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:13px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(0, 10, 31, 21))
        self.label_14.setStyleSheet("color:red;\n"
"font-size:25px;\n"
"font-family:Georgia;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(30, 10, 571, 21))
        self.label_15.setStyleSheet("font-size:15px;\n"
"font-family:Georgia;")
        self.label_15.setObjectName("label_15")
        self.line_7 = QtWidgets.QFrame(self.page_2)
        self.line_7.setGeometry(QtCore.QRect(670, 10, 16, 551))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.stacked_frame.addWidget(self.page_2)
        self.header_frame = QtWidgets.QFrame(self.frame)
        self.header_frame.setGeometry(QtCore.QRect(0, 30, 1221, 91))
        self.header_frame.setStyleSheet("background:rgb(157, 198, 202)")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setLineWidth(0)
        self.header_frame.setObjectName("header_frame")
        self.comboBox = QtWidgets.QComboBox(self.header_frame)
        self.comboBox.setGeometry(QtCore.QRect(1030, 10, 191, 31))
        self.comboBox.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family:Georgia;\n"
"border:5px solid black;\n"
"")
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/Icons/Innactive.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("res/Icons/Active.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        self.comboBox.addItem("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/Icons/Innactive.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        self.pushButton_5 = QtWidgets.QPushButton(self.header_frame)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 30, 171, 31))
        self.pushButton_5.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/Icons/create_profile_addicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.header_frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 281, 31))
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("background:white;")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(60)
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1221, 31))
        self.frame_2.setStyleSheet("background:black;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(1170, 0, 51, 31))
        self.pushButton_4.setStyleSheet("background:white;")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/Icons/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(1130, 0, 21, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("res/Icons/done.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stacked_frame.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_12.setText(_translate("MainWindow", "Switchium"))
        self.label_16.setText(_translate("MainWindow", "An OpenSource Wallpaper Manager"))
        self.label_17.setText(_translate("MainWindow", "<a href=https://google.com>Looking for Help?</a>"))
        self.pushButton.setText(_translate("MainWindow", "Select Wallapaper"))
        self.label.setText(_translate("MainWindow", "    D:\\Pictures\\Images\\wallpaper.jpeg"))
        self.preview_text_label1.setText(_translate("MainWindow", "          Preview:"))
        self.pushButton_2.setText(_translate("MainWindow", "Color"))
        self.label_3.setText(_translate("MainWindow", "Use Solid color"))
        self.label_6.setText(_translate("MainWindow", "Set Interval :"))
        self.label_7.setText(_translate("MainWindow", "Add Overlay"))
        self.label_8.setText(_translate("MainWindow", "   1920"))
        self.label_9.setText(_translate("MainWindow", "1080"))
        self.pushButton_3.setText(_translate("MainWindow", "Color"))
        self.instruction_message1.setText(_translate("MainWindow", "You\'re In Singlepaper Mode !  Press Right Arrow Key for Switch Into Multipaper Mode"))
        self.highlightor_star1.setText(_translate("MainWindow", "  *"))
        self.preview_text_label1_2.setText(_translate("MainWindow", "Next Wallpaper:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "30 M"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1.5 H"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "1 H"))
        self.pushButton_7.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Show changes on preview</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "Show on Preview"))
        self.label_5.setText(_translate("MainWindow", "Papers Shape :"))
        self.label_10.setText(_translate("MainWindow", "* Only Works for ISB"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "jpeg"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "tiff/tiff"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "jpg"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "png"))
        self.label_18.setText(_translate("MainWindow", "Filter extensions"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "Select Directory"))
        self.label_14.setText(_translate("MainWindow", "  *"))
        self.label_15.setText(_translate("MainWindow", "You\'re In Multipaper Mode !  Press Left Arrow Key for Switch Into Singlepaper Mode"))
        self.comboBox.setItemText(0, _translate("MainWindow", " Select Profile"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MidNight"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sunlight"))
        self.pushButton_5.setText(_translate("MainWindow", "Create Profile"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Create Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    Ui_MainWindow().setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())