# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 779)
        MainWindow.setStyleSheet("background:rgb(35, 32, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 80, 1101, 681))
        self.stackedWidget.setMouseTracking(False)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background:white;")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setMidLineWidth(-1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(570, 60, 131, 41))
        self.pushButton.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:15px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 651, 331))
        self.label_2.setStyleSheet("border:4px solid white;\n"
"border-radius:3px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../java_codes/maxresdefault.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(60, 60, 491, 41))
        self.label.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:25px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"border-radius:15px;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(250, 160, 191, 61))
        self.label_4.setStyleSheet("background:rgb(68, 61, 67);\n"
"color:white;\n"
"font-size:17px;\n"
"font-family:Georgia;\n"
"border:3px solid black;\n"
"")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(770, 40, 20, 531))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(21)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 80, 91, 91))
        self.pushButton_2.setStyleSheet("\n"
"border:5px solid black;\n"
"border-radius:45px;\n"
"background:cyan;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Select Wallapaper"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "          Preview:"))
        self.pushButton_2.setText(_translate("MainWindow", "Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    Ui_MainWindow().setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
